import Link from 'next/link';

export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#FDF5ED', color: '#161612' }}>

      <header style={{ padding: '28px 40px', borderBottom: '0.5px solid rgba(22,22,18,0.10)' }}>
        <Link href="/" style={{
          fontFamily: 'var(--font-anton), sans-serif',
          fontSize: '14px',
          color: 'rgba(185,18,18,0.75)',
          letterSpacing: '2px',
          textDecoration: 'none',
        }}>
          TEXTURE
        </Link>
      </header>

      <div style={{ maxWidth: '680px', margin: '0 auto', padding: '60px 40px 100px' }}>

        <h1 style={{ fontFamily: 'var(--font-anton), sans-serif', fontSize: 'clamp(28px, 7vw, 40px)', letterSpacing: '1px', marginBottom: '8px' }}>
          Terms and Conditions
        </h1>
        <p style={{ fontFamily: 'var(--font-geist-mono), monospace', fontSize: '12px', color: 'rgba(22,22,18,0.35)', letterSpacing: '1px', marginBottom: '48px' }}>
          Last updated June 14, 2026
        </p>

        <Section title="Agreement">
          <p>These Terms and Conditions constitute a legally binding agreement between you and Texture LLC ("Company," "we," "us," "our") concerning your access to and use of gettexture.app and the personalized birth chart reading service delivered through it (collectively, the "Services").</p>
          <p>By purchasing or accessing a reading, you agree to these Terms. If you do not agree, do not use the Services.</p>
          <p>Contact us at <a href="mailto:help@gettexture.app">help@gettexture.app</a> or by mail to Texture LLC, Long Beach, California, United States.</p>
        </Section>

        <Section title="The Service">
          <p>Texture is a web-based service that uses artificial intelligence to generate personalized astrology interpretations based on your birth chart. Each reading is a one-time purchase delivered as a permanent URL accessible at any time.</p>
          <p>The Services are intended for personal, reflective use only and are not a substitute for professional advice of any kind.</p>
        </Section>

        <Section title="Purchases and Refunds">
          <p>Readings are purchased through Etsy. Payment processing and order fulfillment policies are subject to Etsy's terms of service in addition to these Terms.</p>
          <p>Because readings involve the generation of personalized content using your birth data, all sales are final once content generation has begun. If you experience a technical issue that prevents you from accessing your reading, contact us at <a href="mailto:help@gettexture.app">help@gettexture.app</a> and we will make it right.</p>
        </Section>

        <Section title="Acceptable Use">
          <p>You agree not to:</p>
          <ul>
            <li>Use the Services for any unlawful or unauthorized purpose</li>
            <li>Reproduce, distribute, or commercialize any AI-generated content from your reading without written permission from Texture LLC</li>
            <li>Attempt to reverse engineer, scrape, or extract content, prompts, or underlying systems</li>
            <li>Provide false birth data to generate a reading for another person without their consent</li>
            <li>Access the Services through automated means</li>
          </ul>
        </Section>

        <Section title="Disclaimer — Astrological Content">
          <p>All astrological interpretations generated by Texture are provided for reflective and personal interest purposes only. They do not constitute medical, psychological, legal, financial, or professional advice of any kind.</p>
          <p>Texture LLC makes no representations or warranties regarding the accuracy, completeness, or fitness of any interpretation for any particular purpose. No professional or advisory relationship of any kind is created between you and Texture LLC by use of the Services. You assume full responsibility for any decisions made based on content generated by Texture.</p>
        </Section>

        <Section title="Disclaimer — AI-Generated Content">
          <p>Interpretations are generated by a large language model trained on astrological tradition and directed at your specific chart configuration. While we have taken care in designing the system and prompts that produce this content, AI-generated output may contain errors, omissions, or inaccuracies. Texture LLC does not warrant that any interpretation is error-free.</p>
        </Section>

        <Section title="Third-Party Services">
          <p>Texture uses third-party service providers to deliver its core functionality. Birth date, time, and location are transmitted to Vercel (vercel.com) for chart calculation. Chart data is transmitted to Anthropic (anthropic.com) for interpretation generation. Your reading data is stored in Supabase (supabase.com). Payments are processed through Etsy and their payment partners.</p>
        </Section>

        <Section title="Data and Privacy">
          <p>Your personal information is handled in accordance with our <Link href="/privacy" style={{ color: 'rgba(185,18,18,0.75)' }}>Privacy Policy</Link>. Your reading is stored in our database and accessible at your permanent URL indefinitely. To request deletion of your data, contact <a href="mailto:help@gettexture.app">help@gettexture.app</a>.</p>
        </Section>

        <Section title="Limitation of Liability">
          <p>To the fullest extent permitted by law, Texture LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Services. Our total liability to you for any claim arising from the Services shall not exceed the amount you paid for your reading.</p>
        </Section>

        <Section title="Governing Law">
          <p>These Terms are governed by the laws of the State of California, United States, without regard to conflict of law principles. Any disputes shall be resolved through binding arbitration in Los Angeles County, California, except that either party may seek injunctive relief in a court of competent jurisdiction.</p>
        </Section>

        <Section title="Changes to These Terms">
          <p>We may update these Terms from time to time. Continued use of the Services after changes constitutes acceptance of the updated Terms.</p>
        </Section>

        <Section title="Contact">
          <p>Texture LLC<br />Long Beach, California, United States<br /><a href="mailto:help@gettexture.app">help@gettexture.app</a></p>
        </Section>

      </div>

      <footer style={{ padding: '24px 40px', borderTop: '0.5px solid rgba(22,22,18,0.10)', display: 'flex', gap: '24px' }}>
        <Link href="/" style={{ fontFamily: 'var(--font-geist-mono), monospace', fontSize: '11px', color: 'rgba(22,22,18,0.35)', letterSpacing: '1px', textDecoration: 'none' }}>HOME</Link>
        <Link href="/privacy" style={{ fontFamily: 'var(--font-geist-mono), monospace', fontSize: '11px', color: 'rgba(22,22,18,0.35)', letterSpacing: '1px', textDecoration: 'none' }}>PRIVACY</Link>
      </footer>

    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: '40px' }}>
      <h2 style={{
        fontFamily: 'var(--font-geist-mono), monospace',
        fontSize: '11px',
        color: 'rgba(22,22,18,0.35)',
        letterSpacing: '2px',
        textTransform: 'uppercase',
        marginBottom: '16px',
        paddingBottom: '8px',
        borderBottom: '0.5px solid rgba(22,22,18,0.10)',
      }}>
        {title}
      </h2>
      <div style={{
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
        fontFamily: 'var(--font-questrial), sans-serif',
        fontSize: 'clamp(14px, 3.5vw, 16px)',
        color: 'rgba(22,22,18,0.80)',
        lineHeight: 1.7,
        letterSpacing: '-0.2px',
      }}>
        {children}
      </div>
    </div>
  );
}
