-- Follow-up to create_transit_and_aspect_calendars.sql: adds two ratified
-- rules to the aspect_calendar documentation that postdate the original
-- migration -- the edge-window drop rule and the dating convention. Safe to
-- run any time -- COMMENT ON is idempotent and touches no data. Run this
-- once, against the same Supabase project, the same way as the original
-- file.

COMMENT ON TABLE aspect_calendar IS
  'All dated sky-sky events -- the five major aspects among tracked bodies (Sun, Mercury, Venus, Mars, Jupiter, Saturn, Uranus, Neptune, Pluto; Moon excluded entirely except inside eclipse rows) plus eclipses -- derived purely from sky_positions (2023-01-01 to 2046-07-31). DATA MODEL LAW: rows are events, content units are windows. Multiple exact rows sharing one continuous orb window (identical window_start and window_end) are ONE story for any content-generation or grouping consumer -- "in orb X to Y, exacting m times" is one block, never m blocks. There is no static limit on exacts per window. Any future consumer must group by the shared window, never by row count. A window a body pair enters but stations and leaves without perfecting is one row with a NULL exact_date -- a valid, factual "no exact" state, not a gap. EDGE-WINDOW RULE (ratified): a window already open on 2023-01-01 (the data''s first day) or still open on 2046-07-31 (the data''s last day) is dropped entirely, never written -- its true start or close falls outside the data, so no window_start, pass count, or "no exact" row is fabricated for it. This table therefore has no rows whose window genuinely straddles either edge of the 2023-2046 range. DATING CONVENTION (ratified): every event is stamped with its actual UTC calendar date -- always the EARLIER of the two daily sky_positions snapshots bracketing the true crossing/exactness moment, never the later snapshot that first reveals the change. See the exact_date column comment for detail.';

COMMENT ON COLUMN aspect_calendar.exact_date IS
  'The exact-perfection date. NULL only for a "no exact" row -- a window the pair entered and left without perfecting. For eclipse rows, this is the eclipse date. DATING CONVENTION (ratified): dated to the earlier of the two daily sky_positions snapshots bracketing the true crossing moment -- e.g. a crossing at 07:40 UTC on the 14th is dated the 14th, never the 15th (whose snapshot is merely the first to show the change already happened). The fractional position within that day is used only to interpolate exact_degree, never to round the date toward the later snapshot.';
